# Generated by Django 2.0.3 on 2018-11-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20181114_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='flat_number',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
